/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.53
 * Generated at: 2026-05-27 02:35:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Model;
import entity.User;
import java.util.List;

public final class allShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("entity.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Model");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>全部用户</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body {\n");
      out.write("            font-family: \"Microsoft YaHei\", Arial, sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            padding: 40px 50px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n");
      out.write("            min-width: 700px;\n");
      out.write("        }\n");
      out.write("        h2 { text-align: center; color: #333; margin-bottom: 30px; }\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        th, td {\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            border: 1px solid #eee;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        th {\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\n");
      out.write("            color: #fff;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        tr:nth-child(even) { background: #f9f9f9; }\n");
      out.write("        tr:hover { background: #f0f0ff; }\n");
      out.write("        .no-data { color: #f5576c; font-size: 18px; text-align: center; margin-bottom: 30px; }\n");
      out.write("        .back-link {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 10px 30px;\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\n");
      out.write("            color: #fff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .back-link:hover { opacity: 0.9; }\n");
      out.write("        .btn-wrap { text-align: center; }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

        request.setCharacterEncoding("UTF-8");
        Model model = new Model();
        List<User> list = model.showAll();
    
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>全部用户列表</h2>\n");
      out.write("        ");
 if (list != null && list.size() > 0) { 
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <th>ID</th>\n");
      out.write("                <th>用户名</th>\n");
      out.write("                <th>邮箱</th>\n");
      out.write("                <th>角色</th>\n");
      out.write("                <th>状态</th>\n");
      out.write("            </tr>\n");
      out.write("            ");
 for (User u : list) { 
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print( u.getId() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( u.getUsername() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( u.getEmail() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( u.getRoleName() );
      out.write("</td>\n");
      out.write("                <td style=\"color:");
      out.print( u.isLocked() ? "#f5576c" : "#43e97b" );
      out.write('"');
      out.write('>');
      out.print( u.isLocked() ? "已锁定" : "正常" );
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </table>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <p class=\"no-data\">暂无用户数据！</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <div class=\"btn-wrap\">\n");
      out.write("            <a href=\"index.jsp\" class=\"back-link\">返回主页</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
