/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.53
 * Generated at: 2026-05-27 02:14:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import entity.User;
import model.Model;
import java.util.List;
import entity.Permission;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("entity.Permission");
    _jspx_imports_classes.add("entity.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Model");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>用户综合管理系统</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body {\n");
      out.write("            font-family: \"Microsoft YaHei\", Arial, sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            padding: 40px 50px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n");
      out.write("            min-width: 500px;\n");
      out.write("        }\n");
      out.write("        h1 { color: #333; margin-bottom: 6px; font-size: 26px; text-align: center; }\n");
      out.write("        .subtitle { color: #888; margin-bottom: 24px; font-size: 14px; text-align: center; }\n");
      out.write("        .user-info {\n");
      out.write("            background: #f8f9ff;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 16px 20px;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .user-info .left { display: flex; align-items: center; gap: 12px; }\n");
      out.write("        .user-info .avatar {\n");
      out.write("            width: 44px; height: 44px; border-radius: 50%;\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\n");
      out.write("            display: flex; justify-content: center; align-items: center;\n");
      out.write("            color: #fff; font-size: 20px; font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .user-info .name { font-size: 16px; font-weight: bold; color: #333; }\n");
      out.write("        .user-info .role {\n");
      out.write("            font-size: 12px; color: #fff; background: #667eea;\n");
      out.write("            padding: 2px 10px; border-radius: 10px; margin-left: 8px;\n");
      out.write("        }\n");
      out.write("        .user-info .email { font-size: 12px; color: #888; }\n");
      out.write("        .btn-logout {\n");
      out.write("            padding: 8px 20px; background: #f5576c; color: #fff;\n");
      out.write("            border: none; border-radius: 6px; font-size: 13px;\n");
      out.write("            cursor: pointer; text-decoration: none;\n");
      out.write("        }\n");
      out.write("        .btn-logout:hover { opacity: 0.9; }\n");
      out.write("        .menu { display: flex; flex-direction: column; gap: 12px; }\n");
      out.write("        .menu a {\n");
      out.write("            display: block; padding: 13px 0; border-radius: 8px;\n");
      out.write("            text-decoration: none; font-size: 15px; font-weight: bold;\n");
      out.write("            color: #fff; transition: transform 0.2s, box-shadow 0.2s;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .menu a:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 6px 20px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("        .menu a.disabled {\n");
      out.write("            opacity: 0.4; pointer-events: none;\n");
      out.write("        }\n");
      out.write("        .btn-insert  { background: linear-gradient(135deg, #43e97b, #38f9d7); color: #333; }\n");
      out.write("        .btn-update  { background: linear-gradient(135deg, #fa709a, #fee140); color: #333; }\n");
      out.write("        .btn-delete  { background: linear-gradient(135deg, #f5576c, #ff6a88); }\n");
      out.write("        .btn-search  { background: linear-gradient(135deg, #4facfe, #00f2fe); color: #333; }\n");
      out.write("        .btn-showall { background: linear-gradient(135deg, #667eea, #764ba2); }\n");
      out.write("        .btn-admin   { background: linear-gradient(135deg, #f093fb, #f5576c); }\n");
      out.write("        .btn-role    { background: linear-gradient(135deg, #4facfe, #00f2fe); color: #333; }\n");
      out.write("        .section-title {\n");
      out.write("            font-size: 13px; color: #999; margin: 12px 0 8px;\n");
      out.write("            border-top: 1px solid #eee; padding-top: 12px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

        User loginUser = (User) session.getAttribute("loginUser");
        if (loginUser == null) {
            response.sendRedirect("login.jsp");
            return;
        }
        Model model = new Model();
        boolean isAdmin = model.hasPermission(loginUser.getRoleId(), "system", "admin");
        boolean canDelete = model.hasPermission(loginUser.getRoleId(), "user", "delete");
        boolean canManageRole = model.hasPermission(loginUser.getRoleId(), "role", "manage");
    
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>用户综合管理系统</h1>\n");
      out.write("        <p class=\"subtitle\">User Management System</p>\n");
      out.write("\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"left\">\n");
      out.write("                <div class=\"avatar\">");
      out.print( loginUser.getUsername().substring(0,1).toUpperCase() );
      out.write("</div>\n");
      out.write("                <div>\n");
      out.write("                    <div>\n");
      out.write("                        <span class=\"name\">");
      out.print( loginUser.getUsername() );
      out.write("</span>\n");
      out.write("                        <span class=\"role\">");
      out.print( loginUser.getRoleName() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"email\">");
      out.print( loginUser.getEmail() );
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"LogoutServlet\" class=\"btn-logout\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"menu\">\n");
      out.write("            <div class=\"section-title\">基本功能</div>\n");
      out.write("            <a href=\"insert.jsp\" class=\"btn-insert\">新增用户</a>\n");
      out.write("            <a href=\"update.jsp\" class=\"btn-update\">修改用户</a>\n");
      out.write("            <a href=\"dele.jsp\" class=\"btn-delete ");
      out.print( canDelete ? "" : "disabled" );
      out.write("\">删除用户");
      out.print( canDelete ? "" : "（无权限）" );
      out.write("</a>\n");
      out.write("            <a href=\"search.jsp\" class=\"btn-search\">查询用户</a>\n");
      out.write("            <a href=\"allShow.jsp\" class=\"btn-showall\">显示全部用户</a>\n");
      out.write("\n");
      out.write("            ");
 if (isAdmin || canManageRole) { 
      out.write("\n");
      out.write("            <div class=\"section-title\">管理功能</div>\n");
      out.write("            ");
 if (isAdmin) { 
      out.write("\n");
      out.write("            <a href=\"admin.jsp\" class=\"btn-admin\">系统管理</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (canManageRole) { 
      out.write("\n");
      out.write("            <a href=\"roleManage.jsp\" class=\"btn-role\">角色权限管理</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
