/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.53
 * Generated at: 2026-05-24 08:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>用户登录</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body {\n");
      out.write("            font-family: \"Microsoft YaHei\", Arial, sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            padding: 40px 50px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n");
      out.write("            min-width: 420px;\n");
      out.write("        }\n");
      out.write("        h2 { text-align: center; color: #333; margin-bottom: 30px; }\n");
      out.write("        .form-group { margin-bottom: 18px; }\n");
      out.write("        .form-group label {\n");
      out.write("            display: block; margin-bottom: 6px; color: #555; font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .form-group input[type=\"text\"],\n");
      out.write("        .form-group input[type=\"password\"] {\n");
      out.write("            width: 100%; padding: 10px 14px; border: 1px solid #ddd;\n");
      out.write("            border-radius: 6px; font-size: 14px; outline: none;\n");
      out.write("        }\n");
      out.write("        .form-group input:focus { border-color: #667eea; }\n");
      out.write("        .captcha-row {\n");
      out.write("            display: flex; gap: 10px; align-items: center;\n");
      out.write("        }\n");
      out.write("        .captcha-row input {\n");
      out.write("            flex: 1; padding: 10px 14px; border: 1px solid #ddd;\n");
      out.write("            border-radius: 6px; font-size: 14px; outline: none;\n");
      out.write("        }\n");
      out.write("        .captcha-row input:focus { border-color: #667eea; }\n");
      out.write("        .captcha-img {\n");
      out.write("            height: 40px; border-radius: 6px; cursor: pointer;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("        }\n");
      out.write("        .btn-submit {\n");
      out.write("            width: 100%; padding: 12px;\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\n");
      out.write("            border: none; border-radius: 6px; font-size: 16px;\n");
      out.write("            font-weight: bold; color: #fff; cursor: pointer; margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        .btn-submit:hover { opacity: 0.9; }\n");
      out.write("        .msg {\n");
      out.write("            text-align: center; color: #f5576c; font-size: 14px;\n");
      out.write("            margin-bottom: 16px; padding: 8px; background: #fff0f0;\n");
      out.write("            border-radius: 6px;\n");
      out.write("        }\n");
      out.write("        .links {\n");
      out.write("            text-align: center; margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .links a {\n");
      out.write("            color: #667eea; text-decoration: none; font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .links a:hover { text-decoration: underline; }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>用户登录</h2>\n");
      out.write("        ");
 String msg = (String) request.getAttribute("msg"); 
      out.write("\n");
      out.write("        ");
 if (msg != null && !msg.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"msg\">");
      out.print( msg );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>用户名</label>\n");
      out.write("                <input type=\"text\" name=\"username\" required placeholder=\"请输入用户名\"\n");
      out.write("                    value=\"");
      out.print( request.getAttribute("username") != null ? request.getAttribute("username") : "" );
      out.write("\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>密码</label>\n");
      out.write("                <input type=\"password\" name=\"password\" required placeholder=\"请输入密码\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>验证码</label>\n");
      out.write("                <div class=\"captcha-row\">\n");
      out.write("                    <input type=\"text\" name=\"captcha\" required placeholder=\"请输入验证码\">\n");
      out.write("                    <img src=\"CaptchaServlet\" class=\"captcha-img\" onclick=\"this.src='CaptchaServlet?t='+new Date().getTime()\" title=\"点击刷新\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <input type=\"submit\" value=\"登 录\" class=\"btn-submit\">\n");
      out.write("        </form>\n");
      out.write("        <div class=\"links\">\n");
      out.write("            <a href=\"register.jsp\">还没有账号？立即注册</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
