/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.53
 * Generated at: 2026-05-27 02:14:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import entity.User;
import entity.Role;
import entity.Permission;
import model.Model;
import java.util.List;

public final class roleManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("entity.Permission");
    _jspx_imports_classes.add("entity.User");
    _jspx_imports_classes.add("entity.Role");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Model");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>角色权限管理</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body {\n");
      out.write("            font-family: \"Microsoft YaHei\", Arial, sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            padding: 40px 50px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n");
      out.write("            min-width: 800px;\n");
      out.write("        }\n");
      out.write("        h2 { text-align: center; color: #333; margin-bottom: 30px; }\n");
      out.write("        .role-section {\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            border: 1px solid #eee;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .role-header {\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\n");
      out.write("            color: #fff;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .role-header .desc { font-size: 12px; opacity: 0.8; }\n");
      out.write("        .role-header .parent { font-size: 11px; background: rgba(255,255,255,0.2); padding: 2px 8px; border-radius: 4px; }\n");
      out.write("        .perm-grid {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 8px;\n");
      out.write("            padding: 16px 20px;\n");
      out.write("        }\n");
      out.write("        .perm-item {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 6px;\n");
      out.write("            padding: 6px 14px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 13px;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .perm-item.granted {\n");
      out.write("            background: #e8f8f0;\n");
      out.write("            border-color: #43e97b;\n");
      out.write("        }\n");
      out.write("        .perm-item.denied {\n");
      out.write("            background: #f9f9f9;\n");
      out.write("            border-color: #eee;\n");
      out.write("            color: #aaa;\n");
      out.write("        }\n");
      out.write("        .perm-item input[type=\"checkbox\"] {\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .perm-item label {\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .perm-action {\n");
      out.write("            font-size: 11px;\n");
      out.write("            color: #888;\n");
      out.write("            margin-left: 4px;\n");
      out.write("        }\n");
      out.write("        .btn-save {\n");
      out.write("            padding: 6px 16px;\n");
      out.write("            background: linear-gradient(135deg, #43e97b, #38f9d7);\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #333;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .btn-save:hover { opacity: 0.9; }\n");
      out.write("        .back-link {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 10px 30px;\n");
      out.write("            background: linear-gradient(135deg, #4facfe, #00f2fe);\n");
      out.write("            color: #333;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .btn-wrap { text-align: center; margin-top: 10px; }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

        User loginUser = (User) session.getAttribute("loginUser");
        if (loginUser == null) { response.sendRedirect("login.jsp"); return; }
        Model model = new Model();
        if (!model.hasPermission(loginUser.getRoleId(), "role", "manage")) {
            response.sendRedirect("index.jsp");
            return;
        }
        List<Role> roles = model.showAllRoles();
        List<Permission> allPerms = model.getAllPermissions();
    
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>角色权限管理（RBAC）</h2>\n");
      out.write("\n");
      out.write("        ");
 for (Role role : roles) { 
      out.write("\n");
      out.write("        ");

            List<Permission> rolePerms = model.getPermissionsByRoleId(role.getId());
        
      out.write("\n");
      out.write("        <div class=\"role-section\">\n");
      out.write("            <div class=\"role-header\">\n");
      out.write("                <div>\n");
      out.write("                    ");
      out.print( role.getRoleName() );
      out.write("\n");
      out.write("                    <span class=\"desc\">");
      out.print( role.getDescription() );
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                ");
 if (role.getParentId() > 0) { 
      out.write("\n");
      out.write("                <span class=\"parent\">继承自父角色</span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"perm-grid\">\n");
      out.write("                <form action=\"RolePermUpdateServlet\" method=\"post\" style=\"display:contents;\">\n");
      out.write("                    <input type=\"hidden\" name=\"roleId\" value=\"");
      out.print( role.getId() );
      out.write("\">\n");
      out.write("                    ");
 for (Permission perm : allPerms) { 
      out.write("\n");
      out.write("                    ");

                        boolean hasPerm = false;
                        for (Permission rp : rolePerms) {
                            if (rp.getId() == perm.getId()) { hasPerm = true; break; }
                        }
                    
      out.write("\n");
      out.write("                    <div class=\"perm-item ");
      out.print( hasPerm ? "granted" : "denied" );
      out.write("\">\n");
      out.write("                        <input type=\"checkbox\" name=\"perm_");
      out.print( perm.getId() );
      out.write("\" id=\"perm_");
      out.print( role.getId() );
      out.write('_');
      out.print( perm.getId() );
      out.write('"');
      out.write(' ');
      out.print( hasPerm ? "checked" : "" );
      out.write(">\n");
      out.write("                        <label for=\"perm_");
      out.print( role.getId() );
      out.write('_');
      out.print( perm.getId() );
      out.write('"');
      out.write('>');
      out.print( perm.getPermissionName() );
      out.write("</label>\n");
      out.write("                        <span class=\"perm-action\">");
      out.print( perm.getResource() );
      out.write(':');
      out.print( perm.getAction() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    <button type=\"submit\" class=\"btn-save\">保存</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"btn-wrap\">\n");
      out.write("            <a href=\"index.jsp\" class=\"back-link\">返回主页</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
